name: "hello world workflow"
# Controls when the action will run. Triggers the workflow on push some to master or production branch
on:
    push:
        branches:
            -master
            -production
    pull_request:
        branches: 
            -master
            -production
            
    workflow_dispatch:        

jobs:
    hello_world:
        runs-on: ubuntu-latest
        steps:
            - name: "print hello worlds"
              run: echo "hello worlds"