name: "morepipeline / workflow" # Name of the pipeline

on:
    push: # Event: Whenever a push is made to the repository on the master branch
        branches:
            - master
            - test


jobs:
    on-push: # Job name
        runs-on: ubuntu-latest
        steps: # Steps to be exucuted in the job
            - name: "Running on master push" # Steps 1
              run: echo "Running on master push"
