name: "morepipeline / workflow" # Name of the pipeline

on:

        branches:
            - master
            - test
    pull_request: # Event: Whenever a pull request is made to the repository
        branches:
            - master
            - test

jobs:
    on-push: # Job name 1

        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps: # Steps to be exucuted in the job
            - name: "Running on master push" # Steps 1
              run: echo "Running on master push"

    on-pull-request: # Job name 2
        if: github.event_name == 'pull_request'

        runs-on: ubuntu-latest
        steps: # Steps to be excuted in the job
            - name: "Running on pull request" # Steps 1
              run: echo "Running on pull request" 
