name: "morepipeline / workflow" # Name of the pipeline

on:

        branches:
            - master
            - test
    pull_request: # Event: Whenever a pull request is made to the repository
        branches:
            - master
    workflow_dispatch:
jobs:
    on-push: # Job name 1

        runs-on: ubuntu-latest
        steps: # Steps to be excuted in the job
            - name: "Running on pull request" # Steps 1
              run: echo "Running on pull request" 
